version: '3.7'

services:
  # identity-resolver:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - MINIO_URL=http://minio:9000
  #     - MINIO_ROOT_USER=minioadmin
  #     - MINIO_ROOT_PASSWORD=minioadmin
  #   depends_on:
  #     - minio

  minio:
    hostname: minio
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9090"
    ports:
      - '9000:9000'
      - '9090:9090'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

    volumes:
      - ${MINIO_DATA_DIR:-./minio_data}:/data
