FROM public.ecr.aws/lambda/nodejs:20

# Set environment variables
ENV MINIO_URL=http://minio:9000
ENV MINIO_ROOT_USER=minioadmin
ENV MINIO_ROOT_PASSWORD=minioadmin

WORKDIR /home/app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

COPY . ${LAMBDA_TASK_ROOT}

# Pass the name of the function handler as an argument to the runtime
CMD ["dist/lambda.handler"]